permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: Dibya Ghosh
url: http://dibya.xyz
description: yo

collections:
  ml:
    output: true

defaults:
  - scope:
      path: ""
      type: ml
    values:
      layout: post